In [72]:
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

In [73]:
def preprocess_text(text):
    text=text.lower()
    text=re.sub(r'[^a-zA-Z0-9\s]','',text)
    words=word_tokenize(text)
    stop_words=set(stopwords.words('english'))
    words=[word for word in words if word not in stop_words ]
    stemmer=PorterStemmer()
    words=[stemmer.stem(word)for word in words]
    preprocess_text=' '.join(words)
    return preprocess_text

In [74]:
#text="Hello i an Neelanjali Sharma i am a student at icfai university"
#preprocess_text(text)

In [75]:
import pandas as pd
try:
    ds=pd.read_csv('combined_data.csv',encoding='ISO-8859-1')
    #print(ds)
except UnicodeDecodeError as e:
    print("Error",e)

In [76]:
ds.isnull().sum()

URL             0
Description     1
Offense        63
Punishment     63
Cognizable     63
Bailable       63
Court          63
dtype: int64

In [77]:
ds.fillna("Not Mentioned",inplace=True)

In [78]:
ds.isnull().sum()

URL            0
Description    0
Offense        0
Punishment     0
Cognizable     0
Bailable       0
Court          0
dtype: int64

In [79]:
ds.duplicated().sum()

2

In [80]:
ds=ds.drop_duplicates()

In [81]:
ds.duplicated().sum()

0

In [82]:
ds.tail(3)

,URL,Description,Offense,Punishment,Cognizable,Bailable,Court
442,https://lawrato.com/indian-kanoon/ipc/section-510,Description of IPC Section 510\nAccording to s...,"Appearing in a public Place, etc., in a State ...",Simple Imprisonment for 24 hours or Fine or Both,Non-Cognizable,Bailable,Any Magistrate
443,https://lawrato.com/indian-kanoon/ipc/section-511,Description of IPC Section 511\nAccording to s...,Attempting to commit offences punishable with ...,Imprisonment for Life or Imprisonment not exce...,Same As for Offence attempted,Same As for Offence attempted,Same As for Offence attempted
444,https://lawrato.com/indian-kanoon/ipc/section-,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned

In [83]:
ds['Combo']=ds['Description']+' '+ ds['Offense']
ds.tail(3)

,URL,Description,Offense,Punishment,Cognizable,Bailable,Court,Combo
442,https://lawrato.com/indian-kanoon/ipc/section-510,Description of IPC Section 510\nAccording to s...,"Appearing in a public Place, etc., in a State ...",Simple Imprisonment for 24 hours or Fine or Both,Non-Cognizable,Bailable,Any Magistrate,Description of IPC Section 510\nAccording to s...
443,https://lawrato.com/indian-kanoon/ipc/section-511,Description of IPC Section 511\nAccording to s...,Attempting to commit offences punishable with ...,Imprisonment for Life or Imprisonment not exce...,Same As for Offence attempted,Same As for Offence attempted,Same As for Offence attempted,Description of IPC Section 511\nAccording to s...
444,https://lawrato.com/indian-kanoon/ipc/section-,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned Not Mentioned

In [84]:
ds['Combo']=ds['Combo'].apply(preprocess_text)
ds.tail()

,URL,Description,Offense,Punishment,Cognizable,Bailable,Court,Combo
440,https://lawrato.com/indian-kanoon/ipc/section-508,Description of IPC Section 508\nAccording to s...,Act caused by inducing a person to believe tha...,1 Year or Fine or Both,Non-Cognizable,Bailable,Any Magistrate,descript ipc section 508 accord section 508 in...
441,https://lawrato.com/indian-kanoon/ipc/section-509,Description of IPC Section 509\nAccording to s...,Uttering any word or making any gesture intend...,Simple imprisonment for 3 years + Fine,Cognizable,Bailable,Any Magistrate,descript ipc section 509 accord section 509 in...
442,https://lawrato.com/indian-kanoon/ipc/section-510,Description of IPC Section 510\nAccording to s...,"Appearing in a public Place, etc., in a State ...",Simple Imprisonment for 24 hours or Fine or Both,Non-Cognizable,Bailable,Any Magistrate,descript ipc section 510 accord section 510 in...
443,https://lawrato.com/indian-kanoon/ipc/section-511,Description of IPC Section 511\nAccording to s...,Attempting to commit offences punishable with ...,Imprisonment for Life or Imprisonment not exce...,Same As for Offence attempted,Same As for Offence attempted,Same As for Offence attempted,descript ipc section 511 accord section 511 in...
444,https://lawrato.com/indian-kanoon/ipc/section-,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,mention mention

In [85]:
new_ds=ds[['Description','Offense','Punishment','Cognizable','Bailable','Court','Combo']]
#new_ds

In [86]:
new_ds['Combo']=new_ds['Combo'].apply(lambda x:"".join(x))
new_ds

C:\Users\user\AppData\Local\Temp\ipykernel_20828\89218900.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_ds['Combo']=new_ds['Combo'].apply(lambda x:"".join(x))

,Description,Offense,Punishment,Cognizable,Bailable,Court,Combo
0,Description of IPC Section 140\nAccording to s...,Wearing the dress or carrying any token used b...,3 Months or Fine or Both,Cognizable,Bailable,Any Magistrate,descript ipc section 140 accord section 140 in...
1,Description of IPC Section 127\nAccording to s...,Receiving property taken by war or depredation...,7 Years + Fine + forfeiture of property,Cognizable,Non-Bailable,Court of Session,descript ipc section 127 accord section 127 in...
2,Description of IPC Section 128\nAccording to s...,Public servant voluntarily allowing prisoner o...,Imprisonment for Life or 10 Years + Fine,Cognizable,Non-Bailable,Court of Session,descript ipc section 128 accord section 128 in...
3,Description of IPC Section 129\nAccording to s...,Public servant negligently suffering prisoner ...,Simple Imprisonment 3 Years + Fine,Cognizable,Bailable,Magistrate First Class,descript ipc section 129 accord section 129 in...
4,Description of IPC Section 130\nAccording to s...,"Aiding escape of, rescuing or harbouring, such...",Imprisonment for Life or 10 Years + Fine,Cognizable,Non-Bailable,Court of Session,descript ipc section 130 accord section 130 in...
...,...,...,...,...,...,...,...
440,Description of IPC Section 508\nAccording to s...,Act caused by inducing a person to believe tha...,1 Year or Fine or Both,Non-Cognizable,Bailable,Any Magistrate,descript ipc section 508 accord section 508 in...
441,Description of IPC Section 509\nAccording to s...,Uttering any word or making any gesture intend...,Simple imprisonment for 3 years + Fine,Cognizable,Bailable,Any Magistrate,descript ipc section 509 accord section 509 in...
442,Description of IPC Section 510\nAccording to s...,"Appearing in a public Place, etc., in a State ...",Simple Imprisonment for 24 hours or Fine or Both,Non-Cognizable,Bailable,Any Magistrate,descript ipc section 510 accord section 510 in...
443,Description of IPC Section 511\nAccording to s...,Attempting to commit offences punishable with ...,Imprisonment for Life or Imprisonment not exce...,Same As for Offence attempted,Same As for Offence attempted,Same As for Offence attempted,descript ipc section 511 accord section 511 in...
444,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,mention mention

In [87]:
import pickle
with open("preprocess_data.pkl",'wb') as file:
    pickle.dump(new_ds,file)

In [88]:
new_ds=pickle.load(open('preprocess_data.pkl','rb'))
new_ds.tail(2)

,Description,Offense,Punishment,Cognizable,Bailable,Court,Combo
443,Description of IPC Section 511\nAccording to s...,Attempting to commit offences punishable with ...,Imprisonment for Life or Imprisonment not exce...,Same As for Offence attempted,Same As for Offence attempted,Same As for Offence attempted,descript ipc section 511 accord section 511 in...
444,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,Not Mentioned,mention mention

In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
nltk.download('punkt')
from docx import document
import textract
from PyPDF2 import PdfReader
#pip install docx
#pip install python-docx
#pip install textract
#pip install PyPDF2

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [92]:
from sentence_transformers import SentenceTransformer,util
model=SentenceTransformer('paraphrase-MiniLM-L6-v2')
def suggest_section(complaint,dataset,mini_suggestions=5):
    preprocessed_complaint=preprocess_text(complaint)
    complaint_embedding=model.encode(preprocessed_complaint)
    section_embeddings=model.encode(dataset['Combo'].tolist())
    similarities=util.pytorch_cos_sim(complaint_embedding,section_embeddings)[0]
    similarity_threshold=0.9
    relevant_indices=[]
    while len(relevant_indices)<mini_suggestions and similarity_threshold>0:
        relevant_indices=[i for i , sim in enumerate(similarities) if sim>similarity_threshold]
        similarity_threshold=0.05
    sorted_indices=sorted(relevant_indices,key=lambda i:similarities[i],reverse=True)
    suggestions=dataset.iloc[sorted_indices][['Description','Offense','Punishment','Cognizable','Bailable','Court','Combo']].to_dict(orient='records')
    return suggestions

In [93]:
complaint=input("Enter crime Description :")
suggest_section=suggest_section(complaint,new_ds)
if suggest_section:
    for suggestion in suggest_section:
        print("Description:" ,suggestion['Description'])
        print("Offense:" ,suggestion['Offense'])
        print("Punishment:" ,suggestion['Punishment'])

Description: Description of IPC Section 302
According to section 302 of Indian penal code, Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine.


IPC 302 in Simple Words
Section 302 of the Indian Penal Code states that anyone who commits murder can be punished with the death penalty or life imprisonment, and may also be fined.

Cited by
Ramdeo Rai Yadav vs State Of Bihar
Mohammad Irfan vs State Of Karnataka
Prasad Pradhan vs The State Of Chhattisgarh
Nandu Singh vs The State Of Madhya Pradesh
Kala Singh Gurnam Singh vs The State Of Punjab
Offense: Murder
Punishment: Death or Imprisonment for Life + Fine
Description: Description of IPC Section 303
According to section 303 of Indian penal code, Whoever, being under sentence of imprisonment for life, commits murder, shall be punished with death.


IPC 303 in Simple Words
Section 303 of the Indian Penal Code states that if a person, who is already serving a life imprisonment sentence, commits murder, they can be punished with the death penalty.
Offense: Murder by a person under Sentence of imprisonment for life
Punishment: Death
Description: Description of IPC Section 307
According to section 307 of Indian penal code, Whoever does any act with such intention or knowledge, and under such circumstances that, if he by that act caused death, he would be guilty of murder, shall be punished with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine; and, if hurt is caused to any person by such act, the offender shall be liable either to imprisonment for life, or to such punishment as is hereinbefore mentioned.
Attempts by Life Convicts: When any person offending under this section is under sentence of imprisonment for life, he may, if hurt is caused, be punished with death.


IPC 307 in Simple Words
Section 307 of the Indian Penal Code states that if someone does an act with the intention or knowledge that, if it caused death, it would be considered murder, they can be punished with imprisonment for up to ten years, and may also be fined; if the act causes hurt to any person, the offender may be sentenced to life imprisonment or the punishment mentioned before, and if the offender is already serving life imprisonment, they can be punished with death if hurt is caused.

Cited by
Surinder Singh vs The Union Territory Of Chandigarh
Shaukat vs State Of Uttaranchal
Hikmat Ali Khan vs Ishwar Prasad Arya
The State Of Madhya Pradesh vs Kanha
The State Of Madhya Pradesh vs Harjeet Singh
Offense: Attempt to murder
Punishment: 10 Years + Fine
Description: Description of IPC Section 364
According to section 364 of Indian penal code, Whoever kidnaps or abducts any person in order that such person may be murdered or may be so disposed of as to be put in danger of being murdered, shall be punished with imprisonment for life or rigorous imprisonment for a term which may extend to ten years, and shall also be liable to fine.


IPC 364 in Simple Words
In the Indian Penal Code, anyone who kidnaps or abducts a person with the intention of either murdering them or putting them in danger of being murdered can be punished with life imprisonment or rigorous imprisonment for up to ten years, along with a fine.

Cited by
Rafiq Ahmed at Rafi vs State Of Uttar Pradesh
Kishore Bhadke vs State Of Maharashtra
Irappa Siddappa Murgannavar vs The State Of Karnataka
Baldev Singh vs State Of Punjab
Ishwari Lal Yadav vs State Of Chhattisgarh
Offense: Kidnapping or abducting in order to murder
Punishment: Imprisonment for Life or Rigorous Imprisonment for 10 Years + Fine
Description: Description of IPC Section 310
According to section 310 of Indian penal code, Whoever, at any time after the passing of this Act, shall have been habitually associated with any other or others for the purpose of committing robbery or child-stealing by means of or accompanied with murder, is a thug.


IPC 310 in Simple Words
Section 310 of the Indian Penal Code states that anyone who, after the passing of this Act, is regularly associated with others to commit robbery or child-stealing along with murder is considered a thug.
Offense: Not Mentioned
Punishment: Not Mentioned
Description: Description of IPC Section 148
According to section 148 of Indian penal code, Whoever is guilty of rioting, being armed with a deadly weapon or with anything which, used as a weapon of offence, is likely to cause death, shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.


IPC 148 in Simple Words
If someone takes part in a riot while being armed with a deadly weapon or anything likely to cause death, they can be punished with up to three years in jail, a fine, or both.
Offense: Rioting armed with deadly Weapon
Punishment: 3 Years or Fine or Both
Description: Description of IPC Section 304
According to section 304 of Indian penal code, Whoever commits culpable homicide not amounting to murder shall be punished with imprisonment for life, or imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine, if the act by which the death is caused is done with the intention of causing death, or of causing such bodily injury as is likely to cause death;
or with imprisonment of either description for a term which may extend to ten years, or with fine, or with both, if the act is done with the knowledge that it is likely to cause death, but without any intention to cause death, or to cause such bodily injury as is likely to cause death.


IPC 304 in Simple Words
Section 304 of the Indian Penal Code states that if someone commits culpable homicide (causing death without intending to commit murder), they can be punished with life imprisonment or imprisonment for up to ten years, and may also be fined, depending on whether the act was done with the intention to cause death or with the knowledge that it is likely to cause death.

Cited by
Paul vs The State Of Kerala
Sharad Birdhi Chand Sarda vs State Of Maharashtra
Sarla Mudgal, President vs Union Of India
The State Of Punjab vs Gurmit Singh
Offense: Culpable homicide not amounting to murder, If act by which the death is caused is done with intention of causing death, etc.
Punishment: Imprisonment for Life or 10 Years + Fine
Description: Description of IPC Section 300
According to section 300 of Indian penal code,
Except in the cases hereinafter excepted, culpable homicide is murder, if the act by which the death is caused is done with the intention of causing death, or-

2ndly.-If it is done with the intention of causing such bodily injury as the offender knows to be likely to cause the death of the person to whom the harm is caused, or-

3rdly.-If it is done with the intention of causing bodily injury to any person and the bodily injury intended to be inflicted is sufficient in the ordinary course of nature to cause death, or-

4thly.-If the person committing the act knows that it is so imminently dangerous that it must, in all probability, cause death, or such bodily injury as is likely to cause death, and commits such act without any excuse for incurring the risk of causing death or such injury as aforesaid.


IPC 300 in Simple Words
According to section 300 of the Indian Penal Code, culpable homicide is considered murder if the act is done with the intention of causing death or causing bodily injury likely to cause death, or if the act is so dangerous that it is likely to cause death or serious bodily injury and is done without any excuse for taking such a risk.

Illustrations

(a) A shoots Z with the intention of killing him. Z dies in consequence. A commits murder.
(b) A, knowing that Z is labouring under such a disease that a blow is likely to cause his death, strikes him with the intention of causing bodily injury. Z dies in consequence of the blow. A is guilty of murder, although the blow might not have been sufficient in the ordinary course of nature to cause the death of a person in a sound state of health. But if A, not knowing that Z is labouring under any disease, gives him such a blow as would not in the ordinary course of nature kill a person in a sound state of health, here A, although he may intend to cause bodily injury, is not guilty of murder, if he did not intend to cause death, or such bodily injury as in the ordinary course of nature would cause death.
(c) A intentionally gives Z a sword-cut or club-wound sufficient to cause the death of a man in the ordinary course of nature. Z dies in consequence. Here A is guilty of murder, although he may not have intended to cause Z's death.
(d) A without any excuse fires a loaded cannon into a crowd of persons and kills one of them. A is guilty of murder, although he may not have had a premeditated design to kill any particular individual.

Exception 1.-When culpable homicide is not murder.-Culpable homicide is not murder if the offender, whilst deprived of the power of self-control by grave and sudden provocation, causes the death of the person who gave the provocation or causes the death of any other person by mistake or accident.

The above exception is subject to the following provisos:-

First.-That the provocation is not sought or voluntarily provoked by the offender as an excuse for killing or doing harm to any person.

Secondly.-That the provocation is not given by anything done in obedience to the law, or by a public servant in the lawful exercise of the powers of such public servant.

Thirdly.-That the provocation is not given by anything done in the lawful exercise of the right of private defence.

Explanation.-Whether the provocation was grave and sudden enough to prevent the offence from amounting to murder is a question of fact.

Illustrations

(a) A, under the influence of passion excited by a provocation given by Z, intentionally kills Y, Z's child. This is murder, in as much as the provocation was not given by the child, and the death of the child was not caused by accident or misfortune in doing an act caused by the provocation.
(b) Y gives grave and sudden provocation to A. A, on this provocation, fires a pistol at Y, neither intending nor knowing himself to be likely to kill Z, who is near him, but out of sight. A kills Z. Here A has not committed murder, but merely culpable homicide.
(c) A is lawfully arrested by Z, a bailiff. A is excited to sudden and violent passion by the arrest, and kills Z. This is murder, inasmuch as the provocation was given by a thing done by a public servant in the exercise of his powers.
(d) A appears as a witness before Z, a Magistrate. Z says that he does not believe a word of A's deposition, and that A has perjured himself. A is moved to sudden passion by these words, and kills Z. This is murder.
(e)A attempts to pull Z's nose. Z, in the exercise of the right of private defence, lays hold of A to prevent him from doing so. A is moved to sudden and violent passion in consequence, and kills Z. This is murder, inasmuch as the provocation was giving by a thing done in the exercise of the right of private defence.
(f) Z strikes B. B is by this provocation excited to violent rage. A, a bystander, intending to take advantage of B's rage, and to cause him to kill Z, puts a knife into B's hand for that purpose. B kills Z with the knife. Here B may have committed only culpable homicide, but A is guilty of murder.

Exception 2.-Culpable homicide is not murder if the offender in the exercise in good faith of the right of private defence of person or property, exceeds the power given to him by law and causes the death of the person against whom he is exercising such right of defence without premeditation, and without any intention of doing more harm than is necessary for the purpose of such defence.

Illustration

Z attempts to horsewhip A, not in such a manner as to cause grievous hurt to A. A draws out a pistol. Z persists in the assault. A believing in good faith that he can by no other means prevent himself from being horsewhipped, shoots Z dead. A has not committed murder, but only culpable homicide.

Exception 3.-Culpable homicide is not murder if the offender, being a public servant or aiding a public servant acting for the advancement of public justice, exceeds the powers given to him by law, and causes death by doing an act which he, in good faith, believes to be lawful and necessary for the due discharge of his duty as such public servant and without ill-will towards the person whose death is caused.

Exception 4.-Culpable homicide is not murder if it is committed without premeditation in a sudden fight
Offense: Not Mentioned
Punishment: Not Mentioned
Description: Description of IPC Section 324
According to section 324 of Indian penal code, Whoever, except in the case provided for by section 334, voluntarily causes hurt by means of any instrument for shooting, stabbing or cutting, or any instrument which, used as a weapon of offence, is likely to cause death, or by means of fire or any heated substance, or by means of any poison or any corrosive substance, or by means of any explosive substance or by means of any substance which it is deleterious to the human body to inhale, to swallow, or to receive into the blood, or by means of any animal, shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.


IPC 324 in Simple Words
Section 324 of the Indian Penal Code states that if someone voluntarily causes hurt using dangerous means or instruments, they can be punished with imprisonment for up to three years, or a fine, or both.

Cited by
Mohammad Khalil Chisti vs State Of Rajasthan
Md Abdul Sufan Laskar and Ors vs State Of Assam
Abdul Rashid Abdul Rahiman Patel vs State Of Maharashtra
Anwarul Haq vs The State Of Uttar Pradesh
Subramani And Ors vs State Of Tamil Nadu
Offense: Voluntarily causing hurt by dangerous weapons or means
Punishment: 3 Years or Fine or Both
Description: Description of IPC Section 428
According to section 428 of Indian penal code, Whoever commits mischief by killing, poisoning, maiming or rendering useless any animals or animal of the value of the ten rupees or upwards, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.


IPC 428 in Simple Words
If someone intentionally harms or kills animals worth ten rupees or more, they can be punished with imprisonment up to two years, or fined, or both.
Offense: Mischief by killing, poisoning, maiming or rendering useless any animal of the value of 10 rupees or upwards
Punishment: 2 Years or Fine or Both
Description: Description of IPC Section 396
According to section 396 of Indian penal code, If any one of five or more persons, who are conjointly committing dacoity, commits murder in so committing dacoity, every one of those persons shall be punished with death, or imprisonment for life, or rigorous imprisonment for a term which may extend to ten years, and shall also be liable to fine.


IPC 396 in Simple Words
If any one of five or more persons involved in dacoity commits murder during the act, all of them will be punished with death, life imprisonment, or rigorous imprisonment up to ten years, and may also face a fine.
Offense: Murder in Dacoity
Punishment: Death, Imprisonment for Life, or Rigorous Imprisonment for 10 Years + Fine
Description: Description of IPC Section 397
According to section 397 of Indian penal code, If, at the time of committing robbery or dacoity, the offender uses any deadly weapon, or causes grievous hurt to any person, so attempts to cause death or grievous hurt to any person, the imprisonment with which such offender shall be punished shall not be less than seven years.


IPC 397 in Simple Words
If a person commits robbery or dacoity while using a deadly weapon or causing grievous hurt, they will be punished with imprisonment of at least seven years.

Cited by
Gilbert Pereira vs State Of Karnataka
Deepak at Wireless vs State Of Maharashtra
Oma at Omprakash and Anr vs State Of Tamilnadu
Ashfaq vs State Govt Of Nct Of Delhi
Dilawar Singh vs State Of Delhi
Offense: Robber or Dacoity, with attempt to cause death or grievous hurt
Punishment: Rigorous Imprisonment for not less than 7 Years
Description: Description of IPC Section 308
According to section 308 of Indian penal code, Whoever does any act with such intention or knowledge and under such circumstances that, if he by that act caused death, he would be guilty of culpable homicide not amounting to murder, shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both; and, if hurt is caused to any person by such act, shall be punished with imprisonment of either description for a term which may extend to seven years, or with fine, or with both.


IPC 308 in Simple Words
Section 308 of the Indian Penal Code states that if someone does an act with the intention or knowledge that, if it caused death, it would be considered culpable homicide not amounting to murder, they can be punished with imprisonment for up to three years, or a fine, or both; if the act causes hurt to any person, the punishment can be imprisonment for up to seven years, or a fine, or both.

Cited by
Shiv Kumar Jatia vs State Of Nct Of Delhi
Sumer Singh vs Surajbhan Singh
Shaukat vs State Of Uttaranchal
Roop Chand Lala vs State Nct Of Delhi
Sheetala Prasad and Ors vs Sri Kant and Anr
Offense: Attempt to commit culpable homicide
Punishment: 3 Years or Fine or Both
Description: Description of IPC Section 326
According to section 326 of Indian penal code, Whoever, except in the case provided for by section 335, voluntarily causes grievous hurt by means of any instrument for shooting, stabbing or cutting, or any instrument which, used as a weapon of offence, is likely to cause death, or by means of fire or any heated substance, or by means of any poison or any corrosive substance, or by means of any explosive substance, or by means of any substance which it is deleterious to the human body to inhale, to swallow, or to receive into the blood, or by means of any animal, shall be punished with imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.


IPC 326 in Simple Words
Section 326 of the Indian Penal Code states that if someone voluntarily causes severe injuries using various dangerous means or instruments, they can be punished with life imprisonment or imprisonment for up to ten years, and may also be fined.

Cited by
Sanjay Dutt vs State Of Maharashtra
State Of Maharashtra vs Kashirao
Devi Singh vs The State Of Madhya Pradesh
Sahebrao Arjun Hon vs Raosaheb
The State Of Himachal Pradesh vs Vijay Kumar Alias Pappu
Offense: Voluntarily causing grievous hurt by dangerous weapons or means
Punishment: Imprisonment for Life or 10 Years + Fine
Description: Description of IPC Section 304B
According to section 304B of Indian penal code,
Where the death of a woman is caused by any burns or bodily injury or occurs otherwise than under normal circumstances within seven years of her marriage and it is shown that soon before her death she was subjected to cruelty or harassment by her husband or any relative of her husband for, or in connection with, any demand for dowry, such death shall be called dowry death, and such husband or relative shall be deemed to have caused her death.
Whoever commits dowry death shall be punished with imprisonment for a term which shall not be less than seven years but which may extend to imprisonment for life.


IPC 304B in Simple Words