In [1]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:

from nltk.stem import PorterStemmer

def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    
    # Remove punctuation and special characters
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    
    # Tokenize the text
    words = word_tokenize(text)
    
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]
    
    # Stem words
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words]
    
    # Join the words back into a single string
    preprocessed_text = ' '.join(words)
    
    return preprocessed_text
a1="List is collection of non homogenious data type it is mutable in nature"
a2=" "
a3=" "
cleaned_audio_text=preprocess_text(a1)


print(cleaned_audio_text)

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\user/nltk_data'
    - 'c:\\Program Files\\Python313\\nltk_data'
    - 'c:\\Program Files\\Python313\\share\\nltk_data'
    - 'c:\\Program Files\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\user\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [4]:
import pandas as pd

ds = pd.read_csv("question_set - Copy.csv", encoding='latin1')
ds

,sr_no,question,ans,ans 1
0,1,What are the subsets /commands of SQL?,Data definition language (DDL): It defines the...,Data definition language (DDL): It defines the...
1,2,what are CRUD operations and what are their uses?,"CREATE - To create databases, tables, insert t...","CREATE - To create databases, tables, insert t..."
2,3,Difference between WHERE and HAVING clause in ...,The WHERE clause is used to filter rows before...,The WHERE clause is used to filter rows before...
3,4,Difference between the PRIMARY key and the UNI...,The PRIMARY key constraint is used to uniquely...,The PRIMARY key constraint is used to uniquely...
4,5,"Difference between TRUNCATE, DELETE and DROP i...",TRUNCATE is used to delete all the rows from a...,TRUNCATE is used to delete all the rows from a...
5,6,Difference between CHAR and VARCHAR data types...,CHAR and VARCHAR are both data types used to \...,CHAR and VARCHAR are both data types used to \...
6,7,Difference between LEFT and RIGHT OUTER JOIN i...,"Both are outer joins, in LEFT outer join, all ...","Both are outer joins, in LEFT outer join, all ..."
7,8,What is SELF JOIN in SQL?,When we join two instances of tables it's call...,When we join two instances of tables it's call...
8,9,Can you use a JOIN without specifying a join c...,"Yes, you can use a CROSS JOIN (Cartesian Join)...","Yes, you can use a CROSS JOIN (Cartesian Join)..."
9,10,"What are aggregate functions in SQL, and what ...",Aggregate functions are SQL functions used to ...,Aggregate functions are SQL functions used to ...
10,11,What is the difference between the COUNT funct...,COUNT function with DISTINCT counts only the d...,COUNT function with DISTINCT counts only the d...
11,12,Explain the usage of the GROUP BY clause with ...,The GROUP BY clause is used to group rows base...,The GROUP BY clause is used to group rows base...
12,13,How do you create a view in SQL?,"To create a view in SQL, you use the CREATE VI...","To create a view in SQL, you use the CREATE VI..."
13,14,"What is database normalization, and why is it ...",Database normalization is the process of organ...,Database normalization is the process of organ...
14,15,Explain the ACID properties of transactions.,"ACID stands for Atomicity, Consistency, Isolat...","ACID stands for Atomicity, Consistency, Isolat..."
15,16,What is the purpose of the ORDER BY clause in ...,The ORDER BY clause within Window Functions de...,The ORDER BY clause within Window Functions de...
16,17,"What is a database trigger, and what events ca...",A database trigger is a special type of stored...,A database trigger is a special type of stored...
17,18,What are SQL subquries?,"Subqueries, also known as nested queries or in...","Subqueries, also known as nested queries or in..."

In [5]:
ds["ans1"]=ds["ans 1"].astype(str).apply(preprocess_text)

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\user/nltk_data'
    - 'c:\\Program Files\\Python313\\nltk_data'
    - 'c:\\Program Files\\Python313\\share\\nltk_data'
    - 'c:\\Program Files\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\user\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [ ]:
new_ds=ds[['sr_no','question','ans','ans 1']]
new_ds['ans1']=new_ds['ans 1'].apply(lambda x:"".join(x))

In [ ]:
import pickle
with open("preprocess_data_copy.pkl",'wb')as file:
    pickle.dump(new_ds,file)

In [ ]:
import pickle
new_ds = pickle.load(open('preprocess_data_copy.pkl', 'rb'))
new_ds

,sr_no,question,ans,ans 1,ans1
0,1,What are the subsets /commands of SQL?,Data definition language (DDL): It defines the...,Data definition language (DDL): It defines the...,Data definition language (DDL): It defines the...
1,2,what are CRUD operations and what are their uses?,"CREATE - To create databases, tables, insert t...","CREATE - To create databases, tables, insert t...","CREATE - To create databases, tables, insert t..."
2,3,Difference between WHERE and HAVING clause in ...,The WHERE clause is used to filter rows before...,The WHERE clause is used to filter rows before...,The WHERE clause is used to filter rows before...
3,4,Difference between the PRIMARY key and the UNI...,The PRIMARY key constraint is used to uniquely...,The PRIMARY key constraint is used to uniquely...,The PRIMARY key constraint is used to uniquely...
4,5,"Difference between TRUNCATE, DELETE and DROP i...",TRUNCATE is used to delete all the rows from a...,TRUNCATE is used to delete all the rows from a...,TRUNCATE is used to delete all the rows from a...
5,6,Difference between CHAR and VARCHAR data types...,CHAR and VARCHAR are both data types used to \...,CHAR and VARCHAR are both data types used to \...,CHAR and VARCHAR are both data types used to \...
6,7,Difference between LEFT and RIGHT OUTER JOIN i...,"Both are outer joins, in LEFT outer join, all ...","Both are outer joins, in LEFT outer join, all ...","Both are outer joins, in LEFT outer join, all ..."
7,8,What is SELF JOIN in SQL?,When we join two instances of tables it's call...,When we join two instances of tables it's call...,When we join two instances of tables it's call...
8,9,Can you use a JOIN without specifying a join c...,"Yes, you can use a CROSS JOIN (Cartesian Join)...","Yes, you can use a CROSS JOIN (Cartesian Join)...","Yes, you can use a CROSS JOIN (Cartesian Join)..."
9,10,"What are aggregate functions in SQL, and what ...",Aggregate functions are SQL functions used to ...,Aggregate functions are SQL functions used to ...,Aggregate functions are SQL functions used to ...
10,11,What is the difference between the COUNT funct...,COUNT function with DISTINCT counts only the d...,COUNT function with DISTINCT counts only the d...,COUNT function with DISTINCT counts only the d...
11,12,Explain the usage of the GROUP BY clause with ...,The GROUP BY clause is used to group rows base...,The GROUP BY clause is used to group rows base...,The GROUP BY clause is used to group rows base...
12,13,How do you create a view in SQL?,"To create a view in SQL, you use the CREATE VI...","To create a view in SQL, you use the CREATE VI...","To create a view in SQL, you use the CREATE VI..."
13,14,"What is database normalization, and why is it ...",Database normalization is the process of organ...,Database normalization is the process of organ...,Database normalization is the process of organ...
14,15,Explain the ACID properties of transactions.,"ACID stands for Atomicity, Consistency, Isolat...","ACID stands for Atomicity, Consistency, Isolat...","ACID stands for Atomicity, Consistency, Isolat..."
15,16,What is the purpose of the ORDER BY clause in ...,The ORDER BY clause within Window Functions de...,The ORDER BY clause within Window Functions de...,The ORDER BY clause within Window Functions de...
16,17,"What is a database trigger, and what events ca...",A database trigger is a special type of stored...,A database trigger is a special type of stored...,A database trigger is a special type of stored...
17,18,What are SQL subquries?,"Subqueries, also known as nested queries or in...","Subqueries, also known as nested queries or in...","Subqueries, also known as nested queries or in..."

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [ ]:
new_ds['ans']=new_ds['ans'].apply(stem)

In [ ]:
new_ds['ans']=new_ds['ans'].apply(lambda x:x.lower())

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Function to get the top 1000 repeated words from a text
def get_top_words(text, n=30):
    # Tokenize the text into words
    words = text.split()
    # Count the frequency of each word
    word_freq = {}
    for word in words:
        word_freq[word] = word_freq.get(word, 0) + 1
    # Sort words by frequency and select the top n
    top_words = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)[:n]
    return [word[0] for word in top_words]

# Get the top 1000 repeated words from your resume
top_ans_word = get_top_words(cleaned_audio_text)

# Get the top 1000 repeated words from your dataset (assuming 'new_ds' is your dataset)
all_ans = new_ds['ans'].tolist()
top_dataset_words = get_top_words(' '.join(all_ans))

print(top_dataset_words,"\n\n")
print(top_ans_word)

# Combine the top words from resume and dataset
top_words = list(set(top_ans_word + top_dataset_words))

# Create a TF-IDF vectorizer with the top words
tfidf_vectorizer = TfidfVectorizer(vocabulary=top_words)

# Calculate TF-IDF vectors for your resume and each company description
tfidf_matrix = tfidf_vectorizer.fit_transform([cleaned_audio_text] + all_ans)

# Calculate cosine similarities
cosine_similarities = cosine_similarity(tfidf_matrix[0], tfidf_matrix[1:]).flatten()

# Add similarity scores to the DataFrame
new_ds['Similarity Score'] = cosine_similarities*100

# Rank the job descriptions based on similarity scores
new_ds = new_ds.sort_values(by='Similarity Score', ascending=False)

# Filter job descriptions with a similarity score threshold
threshold = 0.1  # Adjust as needed
filtered_df = new_ds[new_ds['Similarity Score'] >= threshold]

# Sort the DataFrame by Similarity Score in descending order
filtered_df = filtered_df.sort_values(by='Similarity Score', ascending=False)

# Select the top 3 companies with the highest similarity scores
top_5_companies = filtered_df.nlargest(1, 'Similarity Score')

# Assign ratings to your resume for the top 3 companies
top_5_companies['Ans_Rating'] = top_5_companies['Similarity Score']  # Example rating scale

# Display the top 3 companies
print(top_5_companies[['ans','Ans_Rating']])

['the', 'to', 'is', 'a', 'use', 'in', 'and', 'of', 'data', 'tabl', 'row', 'are', 'it', 'or', 'that', 'group', 'on', 'for', 'store', 'from', 'aggreg', 'specifi', 'function', 'ensur', 'be', 'databas', 'as', 'defin', 'database.', 'transact']


['list', 'collect', 'non', 'homogeni', 'data', 'type', 'mutabl', 'natur']
                                                 ans  Ans_Rating
5  char and varchar are both data type use to sto...   16.146845